version: '3.3'
services:
  mysql:
    image: mariadb
    container_name: etnobase_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: always
    networks:
      - etnobase-network

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    container_name: etnobase_wordpress
    volumes:
      - ./wordpress:/var/www/html
    env_file: .env
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DB
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always
    networks:
      - etnobase-network

  nginx:
    image: nginx:latest
    container_name: etnobase_nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    env_file: .env
    ports:
      - 91:80
    links:
      - wordpress
    depends_on:
      - mysql
      - phpmyadmin
    networks:
      - etnobase-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: etnobase_pma
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
        - 92:80
    networks:
      - etnobase-network
  # adminer:
  #   image: adminer
  #   container_name: etnobase_adminer
  #   ports:
  #     - 8080:8080
  #   links:
  #    - db 

volumes:
  phpmyadmin:
    driver: local
  wordpress:
    driver: local
  mysql:
    driver: local

networks:
  etnobase-network:
    driver: bridge